config/routes.rb
Rails.application.routes.draw do
  resources :articles do
  resources :comments, only: [:create,:destroy,:update]
  end
  devise_for :users
  get 'myarticles' => 'articles#myarticles'
  get 'articlesof/:user_id' => 'articles#articlesof', :as =>"articlesof"
  root 'main#index'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
validates :title, presence: true, length:{maximum:50}
validates :description, presence: true, length:{minimum:20}
before_save :set_visit_count
after_create :update_slug
before_update :assign_slug

has_attached_file :cover, styles: { medium: "900x800>", thumb: "600x500>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

scope :ultimos, ->{order("created_at DESC").limit(6)}
def update_visit_count
    self.save if self.visit_count.nil?
    self.update(visit_count: self.visit_count + 1)
end
private

def set_visit_count
  self.visit_count ||= 0
end
end
def assign_slug
    self.slug = "#{ title.parameterize }"
end

def update_slug
    update_attributes slug: assign_slug
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :articles
         has_many :comments
   validates :email, presence: true, uniqueness: true
   validates :password, length:{minimum: 6}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_article
  before_action :authenticate_user!, except:[:index,:show]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end
    def set_article
      @article = Article.find(params[:article_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:article_id, :body)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
 @comments = Comment.all
 @comments = Comment.new
 @articles = Article.paginate(page: params[:page],per_page:6).ultimos
 @article = Article.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/articles/_arti.html.erb
  <h1 class="center-xs top-space">Artículos</h1>
<div class="contenedor1">
  <div class="row around-xs" style="margin:1em;">
    <% @articles.each do |article| %>
    <div class="thumb col-xs-12 col-sm-6 col-md-3"  style="border-bottom: 1px solid black;margin:1em;">
   <h2 class="titulo"><%= link_to article.title, article,class:"titulo" %></h2>
   <span>Por: <%=article.user.email%></span>
       <%= image_tag article.cover.url(:thumb),class:"thumb top-space"%>
       <div class="row">
           <div class="col-xs-12 col-sm-6 flex-start">
             <span><%= article.visit_count %> Visita(s)</span>
           </div>
           <div class="top-space">
             <p><%=truncate(article.description,length:150) %></p>
         </div>
       </div>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/_form.html.erb
<div class=" row middle-xs center-xs main-background1 ">
<div class="col-xs-8 col-md-6 blue big-padding text-left white-text" style="margin:1em;width:auto;">
  <div class="box caja1 middle-xs center-xs" style="margin-left:2.5em;">
    <h1 class="no-margin bold ligth-blue-text no-margin titulo1 text-white">
     Crear Artículo
   </h1>
   <p>Informa alos demas sobre lo que sucede</p>
   <div class="top-space">
   <%= form_with(model: article, local: true) do |form| %>
   <% if article.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

     <ul>
     <% article.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
    <% end %>
       <div class="center-xs ">
         <%= form.text_field :title, id: :article_title, class:"form-control text-white center-xs",require: true %>
         <%= form.label :title ,"Título" %>
       </div>
       <div class="cenetr-xs" >
       Portada:  <%=form.file_field :cover %>

       </div>
       <div class="center-xs ">
         <%= form.text_area :description, id: :article_description, class:"form-control text-white center-xs",require: true %>
         <%=  form.label :description,"Descripción" %>
       </div>
       <div class="row">
       <div class="middle-xs col-xs-12 col-md-12">
       <div>
         <%= form.submit "Crear", class:"btn top-space"  %>
       </div>
       </div>
       </div>

     <% end %>
   </div>
</div>
</div>
</div>

app/views/articles/articlesof.html.erb
<div class="main" >
  <h1 class="center-xs top-space">Artículos</h1>
<div class="contenedor1">
  <div class="row around-xs" >
    <% @articles.each do |article| %>
    <div class="thumb col-xs-12 col-sm-6 col-md-3 " style="border-bottom: 1px solid black;margin:1em;">
   <h2 class="titulo"><%= link_to article.title, article,class:"titulo" %></h2>
   <span>Por: <%=article.user.email%></span>
       <%= image_tag article.cover.url(:thumb),class:"thumb top-space"%>
       <div class="row">
           <div class="col-xs-12 col-sm-6 flex-start">
             <span><%= article.visit_count %> Visita(s)</span>
           </div>
           <div class="top-space">
             <p><%=truncate(article.description,length:150) %></p>
         </div>
       </div>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="main" >
  <h1 class="center-xs top-space">Artículos</h1>
<div class="contenedor1">
  <div class="row around-xs" >
    <% @articles.each do |article| %>
    <div class="thumb col-xs-12 col-sm-6 col-md-3 " style="border-bottom: 1px solid black;margin:1em;">
   <h2 class="titulo"><%= link_to article.title, article,class:"titulo" %></h2>
   <span>Por: <%=article.user.email%></span>
       <%= image_tag article.cover.url(:thumb),class:"thumb top-space"%>
       <div class="row">
           <div class="col-xs-12 col-sm-6 flex-start">
             <span><%= article.visit_count %> Visita(s)</span>
           </div>
           <div class="top-space">
             <p><%=truncate(article.description,length:150) %></p>
         </div>
       </div>
    </div>
    <% end %>
  </div>
  <div class="top-space center-xs large-padding" style="width:100%;">
    <div class="no-list">
      <%= will_paginate @articles %>
    </div>
  </div>
</div>
</div>

app/views/articles/myarticles.html.erb
<div class="main" >
  <h1 class="center-xs top-space">Mis Artículos</h1>
<div class="contenedor1">
  <div class="row around-xs" >
    <% @articles.each do |article| %>
    <div class="thumb col-xs-12 col-sm-6 col-md-3 " style="border-bottom: 1px solid black;margin:1em;">
   <h2 class="titulo"><%= link_to article.title, article,class:"titulo" %></h2>
   <span>Por: <%=article.user.email%></span>
       <%= image_tag article.cover.url(:thumb),class:"thumb top-space"%>
       <div class="row">
           <div class="col-xs-12 col-sm-6 flex-start">
             <span><%= article.visit_count %> Visita(s)</span>
           </div>
           <div class="top-space">
             <p><%=truncate(article.description,length:150) %></p>
         </div>
       </div>
    </div>
    <% end %>
  </div>
  <div class="top-space center-xs large-padding" style="width:100%;">
    <div class="no-list">
      <%= will_paginate @articles %>
    </div>
  </div>
</div>
</div>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="contenedor center-xs">
<div class="top-space">
 <div class="row center-xs">
  <div class="col-xs-8 col-md-10">
<section class="row center-xs">
  <div class="arti center-xs">
    <h1 class="titulo-arti"><%= @article.title %></h1>
    <p class="top-space">Escrito por: <%=@article.user.email%></p>
    <div>
      <%= link_to  "Más articulos de este usuario ", articlesof_path(@article.user.id), :class =>'btn date top-space' %>
    </div>
    <div class="row">
      <div class="main">
        <div class="thumb">
        <%= image_tag @article.cover.url(:thumb,class:"thumb top-space")%>
        </div>

      </div>
    </div>
    <div class="col-md-6 top-space">
      <p>
        Visitas: <%=@article.visit_count%>
      </p>
    </div>
  <div class="descri">
     <%= @article.description %>
  </div>
  </div>

</section>
<aside class="center-xs top-space white large-padding">
  <% if user_signed_in?%>
  <div class="field">
<h3>Escribe tu Comentario</h3>
<%= render "comments/form" %>
</div>
<%end%>
<% unless user_signed_in?%>
  <p class="autor"><a href="<%=new_user_session_path%>" >Inicia Sesión</a> o <a href="<%=new_user_registration_path%>"> Crea una Cuenta </a> para Comentar</p>
<%end%>
</aside>
<div class="row center-xs middle-xs ">
<div class="col-xs-12 col-sm-6"style="width:100%;">
  <ul id="comments-box" style="margin:1em;width:100%;">
  <% @article.comments.each do |comment| %>
  <li class=" top-space white large-padding no-list around-xs">
  <p>  <%= comment.body %></p><p><%= comment.user.email %></p>
  </li>
  <%end%>
  </ul>
</div>
</div>
    </div>
      </div>
    </div>
</div>

app/views/comments/_comment.html.erb
<article class="large-padding white top-space mdl-shadow--2dp">
    <div class="top-space text-left">
       <%= comment.body%>
    </div>

</article>

app/views/comments/_form.html.erb
<div class="center-xs">
<%=
form_for([@article,@comment],remote: true,) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="center-xs">
    <%= form.text_area :body,class:"form-control top-space center-xs" %>
  </div>
  <div class="actions">
    <%= form.submit "Comentar", class:"btn top-space" %>
  </div>
<% end %>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/fotter/_footer.html.erb
<footer>
<div class="container">
  <div class="row middle-xs between-xs" style="padding:10px;">
    <div class="col-xs-12 col-sm-6">
      <div>
      <span> &copy Todos los derechos reservados 2017</span>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="logo">
        RednoticiasChiapas
      </div>
    </div>
  </div>
</div>








</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RednoticiasChiapas</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </head>
  <body>
<header>
<div id="notice_wrapper"> <p style:"<%= 'display:none;' if notice.nil? && alert.nil? %>"><%= notice %><%= alert %></p></div>

  <%if user_signed_in?%>
   <%= render  "navegacion/cuenta" %>
  <%end%>
  <%unless user_signed_in?%>
   <%= render  "navegacion/nocuenta" %>
  <%end%>
</header>
<div class="contenedor">
  <%= yield %>
  <script>
$(document).ready(function() {

  $("#notice_wrapper").fadeIn("slow").delay(2000).fadeOut("slow");

});
  </script>
<footer>
  <%=render "fotter/footer"%>
</footer>
</div>

  </body>
</html>

app/views/main/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>RednoticiasChiapas</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

    </head>
    <body>
    <header class="hero-image center-xs" style="margin:0px;width:100%;">
          <div>
          <h1>Conoce lo que sucede a tú alrededor</h1>
          <p>Mantente siempre informado</p>
      </div>
    </header>
    <div class="social_bar">
    <a href="https://www.facebook.com/Red-Noticias-Chiapas-569819096557814/" class="facebook" target="_blank">Facebook</a>
    </div>
    <section class="main center-xs">
      <%= render "articles/arti"%>
    </section>
  </body>
</html>

app/views/navegacion/_cuenta.html.erb
<div class="logo">
    <span>RednoticiasChiapas</span>
</div>
<nav>
  <a href="<%=root_path%>">Inicio</a>
  <a href="<%=articles_path%>">Artículos</a>
  <a href=" <%=new_article_path%>">Publicar</a>
  <a href="<%=myarticles_path%>">Mís Artículos</a>
<%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
</nav>

app/views/navegacion/_nocuenta.html.erb
<div class="logo">
    <span>RednoticiasChiapas</span>
</div>
<nav>
  <a href="<%=root_path%>">Inicio</a>
  <a href="<%=articles_path%>">Artículos</a>
  <a href=" <%=new_user_session_path%>">Iniciar Sesión</a>
  <a href="<%=new_user_registration_path%>">Crear Cuenta</a>
</nav>